export const DISPLAY_LIST_REQUEST = 'DISPLAY_LIST_REQUEST'
export const DISPLAY_LIST_SUCCESS = 'DISPLAY_LIST_SUCCESS'
export const DISPLAY_LIST_FAIL = 'DISPLAY_LIST_FAIL'

export const DISPLAY_DETAILS_REQUEST = 'DISPLAY_DETAILS_REQUEST'
export const DISPLAY_DETAILS_SUCCESS = 'DISPLAY_DETAILS_SUCCESS'
export const DISPLAY_DETAILS_FAIL = 'DISPLAY_DETAILS_FAIL'

export const DISPLAY_DELETE_REQUEST = 'DISPLAY_DELETE_REQUEST'
export const DISPLAY_DELETE_SUCCESS = 'DISPLAY_DELETE_SUCCESS'
export const DISPLAY_DELETE_FAIL = 'DISPLAY_DELETE_FAIL'

export const DISPLAY_CREATE_REQUEST = 'DISPLAY_CREATE_REQUEST'
export const DISPLAY_CREATE_SUCCESS = 'DISPLAY_CREATE_SUCCESS'
export const DISPLAY_CREATE_FAIL = 'DISPLAY_CREATE_FAIL'
export const DISPLAY_CREATE_RESET = 'DISPLAY_CREATE_RESET'

export const DISPLAY_UPDATE_REQUEST = 'DISPLAY_UPDATE_REQUEST'
export const DISPLAY_UPDATE_SUCCESS = 'DISPLAY_UPDATE_SUCCESS'
export const DISPLAY_UPDATE_FAIL = 'DISPLAY_UPDATE_FAIL'
